[env:xiao_esp32s3]
platform = espressif32@6.12.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_unflags =
    -std=gnu++11
build_flags =
    -std=c++17
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
monitor_filters =
    esp32_exception_decoder
    time
    default
lib_deps =
    h2zero/NimBLE-Arduino@^2.5.0
    symlink://../esp-arduino-ble-scales
